# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  tags:
    include:
      - '*'
  branches:
    include:
      - master
pr:
  - '*'

pool:
  vmImage: 'windows-2019'

strategy:
  matrix:
    ExamplesTls:
      MQTT_USE_TLS: ON
      MQTT_USE_WS: OFF
      MQTT_USE_STR_CHECK: ON
      MQTT_TEST_1: OFF
      MQTT_TEST_2: OFF
      MQTT_TEST_3: OFF
      MQTT_TEST_4: OFF
      MQTT_TEST_5: OFF
      MQTT_TEST_6: OFF
      MQTT_BUILD_EXAMPLES: ON
    ExamplesGnuTls:
      MQTT_USE_TLS: MQTT_TLS_GNUTLS
      MQTT_USE_WS: OFF
      MQTT_USE_STR_CHECK: ON
      MQTT_TEST_1: OFF
      MQTT_TEST_2: OFF
      MQTT_TEST_3: OFF
      MQTT_TEST_4: OFF
      MQTT_TEST_5: OFF
      MQTT_TEST_6: OFF
      MQTT_BUILD_EXAMPLES: ON
    ExamplesWs:
      MQTT_USE_TLS: OFF
      MQTT_USE_WS: ON
      MQTT_USE_STR_CHECK: ON
      MQTT_TEST_1: OFF
      MQTT_TEST_2: OFF
      MQTT_TEST_3: OFF
      MQTT_TEST_4: OFF
      MQTT_TEST_5: OFF
      MQTT_TEST_6: OFF
      MQTT_BUILD_EXAMPLES: ON
    TestGroup1:
      MQTT_USE_TLS: ON
      MQTT_USE_WS: OFF
      MQTT_USE_STR_CHECK: OFF
      MQTT_TEST_1: ON
      MQTT_TEST_2: OFF
      MQTT_TEST_3: OFF
      MQTT_TEST_4: OFF
      MQTT_TEST_5: OFF
      MQTT_TEST_6: OFF
      MQTT_BUILD_EXAMPLES: OFF
    TestGroup2:
      MQTT_USE_TLS: OFF
      MQTT_USE_WS: ON
      MQTT_USE_STR_CHECK: ON
      MQTT_TEST_1: OFF
      MQTT_TEST_2: ON
      MQTT_TEST_3: OFF
      MQTT_TEST_4: OFF
      MQTT_TEST_5: OFF
      MQTT_TEST_6: OFF
      MQTT_BUILD_EXAMPLES: OFF
    TestGroup3:
      MQTT_USE_TLS: ON
      MQTT_USE_WS: OFF
      MQTT_USE_STR_CHECK: ON
      MQTT_TEST_1: OFF
      MQTT_TEST_2: OFF
      MQTT_TEST_3: ON
      MQTT_TEST_4: OFF
      MQTT_TEST_5: OFF
      MQTT_TEST_6: OFF
      MQTT_BUILD_EXAMPLES: OFF
    TestGroup4:
      MQTT_USE_TLS: OFF
      MQTT_USE_WS: ON
      MQTT_USE_STR_CHECK: ON
      MQTT_TEST_1: OFF
      MQTT_TEST_2: OFF
      MQTT_TEST_3: OFF
      MQTT_TEST_4: ON
      MQTT_TEST_5: OFF
      MQTT_TEST_6: OFF
      MQTT_BUILD_EXAMPLES: OFF
    TestGroup5:
      MQTT_USE_TLS: OFF
      MQTT_USE_WS: ON
      MQTT_USE_STR_CHECK: ON
      MQTT_TEST_1: OFF
      MQTT_TEST_2: OFF
      MQTT_TEST_3: OFF
      MQTT_TEST_4: OFF
      MQTT_TEST_5: ON
      MQTT_TEST_6: OFF
      MQTT_BUILD_EXAMPLES: OFF
    TestGroup6:
      MQTT_USE_TLS: MQTT_TLS_OPENSSL
      MQTT_USE_WS: OFF
      MQTT_USE_STR_CHECK: ON
      MQTT_TEST_1: OFF
      MQTT_TEST_2: OFF
      MQTT_TEST_3: OFF
      MQTT_TEST_4: OFF
      MQTT_TEST_5: OFF
      MQTT_TEST_6: ON
      MQTT_BUILD_EXAMPLES: OFF
    TestGroup7:
      MQTT_USE_TLS: OFF
      MQTT_USE_WS: ON
      MQTT_USE_STR_CHECK: ON
      MQTT_TEST_1: OFF
      MQTT_TEST_2: OFF
      MQTT_TEST_3: OFF
      MQTT_TEST_4: OFF
      MQTT_TEST_5: OFF
      MQTT_TEST_6: ON
      MQTT_BUILD_EXAMPLES: OFF
    TestGroup8:
      MQTT_USE_TLS: MQTT_TLS_GNUTLS
      MQTT_USE_WS: OFF
      MQTT_USE_STR_CHECK: OFF
      MQTT_TEST_1: ON
      MQTT_TEST_2: OFF
      MQTT_TEST_3: OFF
      MQTT_TEST_4: OFF
      MQTT_TEST_5: OFF
      MQTT_TEST_6: OFF
      MQTT_BUILD_EXAMPLES: OFF
    TestGroup9:
      MQTT_USE_TLS: MQTT_TLS_GNUTLS
      MQTT_USE_WS: OFF
      MQTT_USE_STR_CHECK: ON
      MQTT_TEST_1: OFF
      MQTT_TEST_2: OFF
      MQTT_TEST_3: ON
      MQTT_TEST_4: OFF
      MQTT_TEST_5: OFF
      MQTT_TEST_6: OFF
      MQTT_BUILD_EXAMPLES: OFF
    TestGroup10:
      MQTT_USE_TLS: MQTT_TLS_GNUTLS
      MQTT_USE_WS: OFF
      MQTT_USE_STR_CHECK: ON
      MQTT_TEST_1: OFF
      MQTT_TEST_2: OFF
      MQTT_TEST_3: OFF
      MQTT_TEST_4: OFF
      MQTT_TEST_5: OFF
      MQTT_TEST_6: ON
      MQTT_BUILD_EXAMPLES: OFF

steps:
- script: |
    choco install --confirm --limitoutput --no-progress openssl
  displayName: 'install openssl'

- script: |
    git submodule update --init --recursive
    mkdir build
    cd build
    set CL=/D_WIN32_WINNT#0x0601
    cmake -A x64 -DMQTT_USE_TLS=%MQTT_USE_TLS% -DMQTT_USE_WS=%MQTT_USE_WS% -DMQTT_USE_STR_CHECK=%MQTT_USE_STR_CHECK% -DMQTT_TEST_1=%MQTT_TEST_1% -DMQTT_TEST_2=%MQTT_TEST_2% -DMQTT_TEST_3=%MQTT_TEST_3% -DMQTT_TEST_4=%MQTT_TEST_4% -DMQTT_TEST_5=%MQTT_TEST_5% -DMQTT_TEST_6=%MQTT_TEST_6% -DMQTT_BUILD_EXAMPLES=%MQTT_BUILD_EXAMPLES% ..
    cmake --build . --config Release -- -verbosity:minimal
    cd test
    set PATH=%BOOST_ROOT%\lib;%PATH%
    ctest -VV
  displayName: 'cmake test'
